import Sidebar from "@/components/Sidebar/Sidebar";
import "../../assets/main.scss";
import { Roboto_Slab } from "next/font/google";

const RobotoSlab = Roboto_Slab({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${RobotoSlab.className} flex `}>
        {/* @ts-expect-error Server Component */}
        <Sidebar /> {children}
      </body>
    </html>
  );
}
