import Sidebar from "@/components/Sidebar/Sidebar";
import "../../assets/main.scss";
import { Roboto_Slab } from "next/font/google";
import { getServerSession } from "next-auth";
import { authOptions } from "@/features/lib/auth";

const RobotoSlab = Roboto_Slab({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`${RobotoSlab.className} `}>
        <Sidebar avatar={session?.user.image} /> {children}
      </body>
    </html>
  );
}
