import "../../assets/main.scss";
import { Roboto_Slab } from "next/font/google";

const RobotoSlab = Roboto_Slab({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${RobotoSlab.className} dark:bg-gray-800 transition-all`}>{children}</body>
    </html>
  );
}
